### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by doms** [rzhade3/rzhade3.github.io#3]
Helloooo, kind sir. 👋🏾 

You should add a _**Dark Mode**_ to your website. Your CSS could be something simple like:
```css
/* default CSS aka your website right now */
body {
  background-color: #fff;     /* background */
  color: #000;                /* for text */
}

/* dark mode */
@media screen and (prefers-color-scheme: dark) {
  body {
    background-color: #222;  /* charcoal instead of complete black */
    color: #fff;
  }
}
```

[`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) will automatically detect whether a user should have light or dark mode. An example would be macOS when it shifts to dark mode at night time. Your website will do the same.

Screenshot for reference:

<p align="center">
	<img width="550" alt="rzhade3 dark mode implementation" src="https://user-images.githubusercontent.com/8808097/100159154-18a3e900-2e62-11eb-9fe2-2ecc6ddb4b2f.png">
</p>

---

If you want more info on the world of dark mode and stuff, I highly recommend [this article on CSS Tricks.](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web)
